# Generated by Django 3.2.5 on 2021-07-28 09:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('birthday', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0, tzinfo=utc), verbose_name='Год Рождения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/', verbose_name='Фото')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок Сайта')),
                ('title_background', models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/', verbose_name='Фон заголовка сайта')),
                ('page_text', models.TextField(verbose_name='Текс страницы')),
                ('page_background', models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/', verbose_name='Фон сайта')),
                ('contact_text', models.TextField(max_length=1000, verbose_name='Контактные данные')),
                ('skills', models.ManyToManyField(to='card.Skills', verbose_name='Навыки')),
            ],
        ),
    ]
