# Generated by Django 3.2.5 on 2021-08-02 07:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='PersonalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('birthday', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0, tzinfo=utc), verbose_name='Год Рождения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='person/photo/%Y/%m/%d/', verbose_name='Фото')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок Сайта')),
                ('title_background', models.ImageField(blank=True, null=True, upload_to='person/title_background/%Y/%m/%d/', verbose_name='Фон заголовка сайта')),
                ('page_text', models.TextField(verbose_name='Текс страницы')),
                ('page_background', models.ImageField(blank=True, null=True, upload_to='person/page_background/%Y/%m/%d/', verbose_name='Фон сайта')),
                ('contact_text', models.TextField(max_length=1000, verbose_name='Контактные данные')),
                ('status', models.BooleanField(default=1, verbose_name='Статус')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='card.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карточки',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название пректа')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание проекта')),
                ('personal_card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='card.personalcard', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='project/img/%Y/%m/%d/', verbose_name='Изображеня')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название Региона')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Регион', to='card.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='personalcard',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='card.projectimages', verbose_name='Изображения'),
        ),
        migrations.AddField(
            model_name='personalcard',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='card.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='personalcard',
            name='skills',
            field=models.ManyToManyField(to='card.Skills', verbose_name='Навыки'),
        ),
    ]
