# Generated by Django 3.2.5 on 2021-08-02 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_skills_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimages',
            options={'verbose_name': 'Изображение проекта', 'verbose_name_plural': 'Изображения проекта'},
        ),
        migrations.RemoveField(
            model_name='personalcard',
            name='images',
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(to='card.ProjectImages'),
        ),
        migrations.AlterField(
            model_name='project',
            name='personal_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.personalcard', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='projectimages',
            name='images',
            field=models.ImageField(upload_to='project/%Y/%m/%d/', verbose_name='Изображеня'),
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='card.country', verbose_name='Страна'),
        ),
    ]
